Data_Preparation:
  test_size: 0.25
  random_state: 30

Train:
  Random_Forest:
    n_estimators: 228
    criterion: 'squared_error'
    max_depth: 17
    max_features: 'sqrt'
    min_samples_split: 10
    min_samples_leaf: 1
    max_samples: 0.8260945842838456
    verbose: 1
    n_jobs: -1
  
  LightGBM:
    n_estimators: 49
    max_depth: 25
    learning_rate: 0.17754792549578896
    subsample: 0.8277333851158997
    min_child_weight: 17
    min_split_gain: 0.021248144717224082
    reg_lambda: 87.41752350223815
    n_jobs: -1